# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import nltk

# Importing the dataset

In [2]:
train = pd.read_csv('../Fine Grained Emotion Recognition for Counselling/dreaddit-train.csv')
test = pd.read_csv('../Fine Grained Emotion Recognition for Counselling/dreaddit-test.csv')

In [3]:
text = train['text'].values
text_test = test['text'].values
y_train = train['label'].values
y_test = test['label'].values

# Cleaning the training data

In [4]:
# Cleaning the data
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re
from nltk.tag.perceptron import PerceptronTagger

tagger=PerceptronTagger()
wordnet = WordNetLemmatizer()
corpus_train = []
corpus_test =[]
tagged = []

In [5]:
for i in range(len(train)):
    review = re.sub('^a-zA-Z^',' ',train['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_train.append(review)

In [6]:
print(corpus_train[1],'\n','\n',corpus_train[2])

hey r/assistance, sure right place post this.. go =) i'm currently student intern sandia national lab working survey help improve marketing outreach effort many school recruit around country. we're looking current undergrad/grad stem student stem student know stem students, would greatly appreciate help take pas along short survey. thank you, everyone help take survey entered drawing chance win one three $50 amazon gcs. 
 
 mom hit newspaper shocked would this, know like play hitting, smacking, striking, hitting violence sort person. send vibe asking universe? yesterday decided take friend go help another "friend" move new place. driving friend moving strike shoulder. address immediately 4th time told things, friend driving nearly get collision another car think high marijuana friend moving backseat like "you understand trying get attention" know thing 5 year old get people attention smacking them, guy 60's.


In [7]:
for i in range(len(test)):
    review = re.sub('^a-zA-Z^',' ',test['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_test.append(review)

# Creating Bag of Words

In [8]:
# Creating the Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train = cv.fit_transform(corpus_train).toarray()
X_test = cv.transform(corpus_test).toarray()

# Parts of speech tag

In [9]:
print(tagged[0][0],'\n',tagged[0][1],'\n',tagged[0][2],'\n',tagged[0][3],'\n',tagged[0][4])


('said', 'VBD') 
 ('felt', 'JJ') 
 ('way', 'NN') 
 ('before,', 'NN') 
 ('suggeted', 'VBD')


# Applying Word2Vec

In [10]:
# # Using Word2Vec
# from gensim.models import Word2Vec
# sentences_train = []
# sentences_test = []

In [11]:
# # Cleaning data for Word2Vec in training dataset
# for i in range(len(train)):
#     review = re.sub('^a-zA-Z^',' ',train['text'][i])
#     review = review.lower()
#     review = review.split()
    
#     review = [word for word in review if word not in set(stopwords.words('english'))]
#     sentences_train.append(review)

In [12]:
# # Cleaning data for Word2Vec in testing dataset
# for i in range(len(test)):
#     review = re.sub('^a-zA-Z^',' ',test['text'][i])
#     review = review.lower()
#     review = review.split()
    
#     review = [word for word in review if word not in set(stopwords.words('english'))]
#     sentences_test.append(review)

In [13]:
# # Training Word2Vec
# train_model = Word2Vec(sentences_train, min_count=1)# if word is present less than 1 skip that word
# #test_model = Word2Vec(sentences_test, min_count=1)# if word is present less than 1 skip that word
# train_model.save("word2vec_train.model")
# #test_model.save("word2vec_test.model")

In [14]:
# words_train = train_model.build_vocab(sentences_train)
# words_test = test_model.build_vocab(sentences_test)

In [15]:
# # training word2vec
# train_model.train(sentences_train,total_examples=train_model.corpus_count,epochs=1001)# corpus_count =2838
# #test_model.train(sentences_test,total_examples=test_model.corpus_count,epochs=1001)

In [16]:
# from gensim.models import KeyedVectors

# # Store just the words + their trained embeddings.
# word_vectors_train = train_model.wv
# word_vectors_train.save("word2vec.wordvectors")
# word_vectors_test = train_model.wv
# # word_vectors_test.save("word2vec.wordvectors")
# # Load back with memory-mapping = read-only, shared across processes.
# wv = KeyedVectors.load("word2vec_train.wordvectors", mmap='r')

# Training Logistic Regression Model on Training set

In [17]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state =0)
lr.fit(X_train,y_train)

LogisticRegression(random_state=0)

# Training K-NN Model on Training set

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
knn.fit(X_train,y_train)

KNeighborsClassifier()

# Training SVM Model on Training set

In [19]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf' , random_state=0)
classifier.fit(X_train,y_train)

SVC(random_state=0)

# Training Naive Bayes Model on Training set

In [20]:
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(X_train,y_train)

GaussianNB()

# Training Decision Tree Model on Training set

In [21]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state =0)
dtc.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Training Random Forest Model on Training set

In [22]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100 , criterion='entropy', random_state=0)
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

# Predicting the test set results

In [23]:
y_pred_lr = lr.predict(X_test)
y_pred_knn = knn.predict(X_test)
y_pred_classifier = classifier.predict(X_test)
y_pred_naive = naive.predict(X_test)
y_pred_dtc = dtc.predict(X_test)
y_pred_rfc = rfc.predict(X_test)

# np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),axis=1)

# Making Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_lr = confusion_matrix(y_test,y_pred_lr)
print('Logistic Regression : \n',cm_lr)
cm_knn = confusion_matrix(y_test,y_pred_knn)
print('K-NN : \n',cm_knn)
cm_classifier = confusion_matrix(y_test,y_pred_classifier)
print('SVM : ',cm_classifier)
cm_naive = confusion_matrix(y_test,y_pred_naive)
print('Naive Bayes : \n',cm_naive)
cm_dtc = confusion_matrix(y_test,y_pred_dtc)
print('Decision Tree Classifier : \n',cm_dtc)
cm_rfc = confusion_matrix(y_test,y_pred_rfc)
print('Random Forest Classifier : \n', cm_rfc)
print('Accuracy of Logistic Regression Classifier is :', accuracy_score(y_test,y_pred_lr),'\n')
print('Accuracy of K_NN Classifier is :', accuracy_score(y_test,y_pred_knn),'\n')
print('Accuracy of SVM Classifier is :' ,accuracy_score(y_test,y_pred_classifier),'\n')
print('Accuracy of Naive Bayes Classifier is :', accuracy_score(y_test,y_pred_naive),'\n')
print('Accuracy of Decision Tree Classifier is :',accuracy_score(y_test,y_pred_dtc),'\n')
print('Accuracy of Random Forest Classifier is :' ,accuracy_score(y_test,y_pred_rfc),'\n')


Logistic Regression : 
 [[236 110]
 [ 92 277]]
K-NN : 
 [[235 111]
 [200 169]]
SVM :  [[234 112]
 [ 95 274]]
Naive Bayes : 
 [[152 194]
 [ 97 272]]
Decision Tree Classifier : 
 [[174 172]
 [128 241]]
Random Forest Classifier : 
 [[188 158]
 [ 59 310]]
Accuracy of Logistic Regression Classifier is : 0.7174825174825175 

Accuracy of K_NN Classifier is : 0.5650349650349651 

Accuracy of SVM Classifier is : 0.7104895104895105 

Accuracy of Naive Bayes Classifier is : 0.593006993006993 

Accuracy of Decision Tree Classifier is : 0.5804195804195804 

Accuracy of Random Forest Classifier is : 0.6965034965034965 



# Using Stemming for the model

In [25]:
# Cleaning the data
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re

stemmer = PorterStemmer()
corpus_train_stem = []
corpus_test_stem = []

In [26]:
for i in range(len(train)):
    review = re.sub('^a-zA-Z^',' ',train['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_train_stem.append(review)

In [27]:
for i in range(len(test)):
    review = re.sub('^a-zA-Z^',' ',test['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_test_stem.append(review)

In [28]:
# Creating the Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_stem = cv.fit_transform(corpus_train_stem).toarray()
X_test_stem = cv.transform(corpus_test_stem).toarray()

In [29]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state =0)
lr.fit(X_train_stem,y_train)

LogisticRegression(random_state=0)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
knn.fit(X_train_stem,y_train)

KNeighborsClassifier()

In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf' , random_state=0)
classifier.fit(X_train_stem,y_train)

SVC(random_state=0)

In [32]:
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(X_train_stem,y_train)

GaussianNB()

In [33]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state =0)
dtc.fit(X_train_stem,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [34]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100 , criterion='entropy', random_state=0)
rfc.fit(X_train_stem,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [35]:
y_pred_lr = lr.predict(X_test_stem)
y_pred_knn = knn.predict(X_test_stem)
y_pred_classifier = classifier.predict(X_test_stem)
y_pred_naive = naive.predict(X_test_stem)
y_pred_dtc = dtc.predict(X_test_stem)
y_pred_rfc = rfc.predict(X_test_stem)

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_lr = confusion_matrix(y_test,y_pred_lr)
print('Logistic Regression : \n',cm_lr)
cm_knn = confusion_matrix(y_test,y_pred_knn)
print('K-NN : \n',cm_knn)
cm_classifier = confusion_matrix(y_test,y_pred_classifier)
print('SVM : ',cm_classifier)
cm_naive = confusion_matrix(y_test,y_pred_naive)
print('Naive Bayes : \n',cm_naive)
cm_dtc = confusion_matrix(y_test,y_pred_dtc)
print('Decision Tree Classifier : \n',cm_dtc)
cm_rfc = confusion_matrix(y_test,y_pred_rfc)
print('Random Forest Classifier : \n', cm_rfc)
print('Accuracy of Logistic Regression Classifier is :', accuracy_score(y_test,y_pred_lr),'\n')
print('Accuracy of K_NN Classifier is :', accuracy_score(y_test,y_pred_knn),'\n')
print('Accuracy of SVM Classifier is :' ,accuracy_score(y_test,y_pred_classifier),'\n')
print('Accuracy of Naive Bayes Classifier is :', accuracy_score(y_test,y_pred_naive),'\n')
print('Accuracy of Decision Tree Classifier is :',accuracy_score(y_test,y_pred_dtc),'\n')
print('Accuracy of Random Forest Classifier is :' ,accuracy_score(y_test,y_pred_rfc),'\n')


Logistic Regression : 
 [[241 105]
 [ 85 284]]
K-NN : 
 [[231 115]
 [197 172]]
SVM :  [[246 100]
 [ 97 272]]
Naive Bayes : 
 [[123 223]
 [ 97 272]]
Decision Tree Classifier : 
 [[185 161]
 [130 239]]
Random Forest Classifier : 
 [[195 151]
 [ 60 309]]
Accuracy of Logistic Regression Classifier is : 0.7342657342657343 

Accuracy of K_NN Classifier is : 0.5636363636363636 

Accuracy of SVM Classifier is : 0.7244755244755244 

Accuracy of Naive Bayes Classifier is : 0.5524475524475524 

Accuracy of Decision Tree Classifier is : 0.593006993006993 

Accuracy of Random Forest Classifier is : 0.7048951048951049 

