# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import nltk

# Importing the dataset

In [2]:
train = pd.read_csv('../Fine Grained Emotion Recognition for Counselling/dreaddit-train.csv')
test = pd.read_csv('../Fine Grained Emotion Recognition for Counselling/dreaddit-test.csv')

In [3]:
text = train['text'].values
text_test = test['text'].values
y_train = train['label'].values
y_test = test['label'].values

# Cleaning the training data

In [4]:
# Cleaning the data
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re
from nltk.tag.perceptron import PerceptronTagger

tagger=PerceptronTagger()
wordnet = WordNetLemmatizer()
corpus_train = []
corpus_test =[]
tagged = []

In [5]:
for i in range(len(train)):
    review = re.sub('^a-zA-Z^',' ',train['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_train.append(review)

In [6]:
print(corpus_train[1],'\n','\n',corpus_train[2])

hey r/assistance, sure right place post this.. go =) i'm currently student intern sandia national lab working survey help improve marketing outreach effort many school recruit around country. we're looking current undergrad/grad stem student stem student know stem students, would greatly appreciate help take pas along short survey. thank you, everyone help take survey entered drawing chance win one three $50 amazon gcs. 
 
 mom hit newspaper shocked would this, know like play hitting, smacking, striking, hitting violence sort person. send vibe asking universe? yesterday decided take friend go help another "friend" move new place. driving friend moving strike shoulder. address immediately 4th time told things, friend driving nearly get collision another car think high marijuana friend moving backseat like "you understand trying get attention" know thing 5 year old get people attention smacking them, guy 60's.


In [7]:
for i in range(len(test)):
    review = re.sub('^a-zA-Z^',' ',test['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_test.append(review)

# Creating Bag of Words

In [8]:
# Creating the Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train = cv.fit_transform(corpus_train).toarray()
X_test = cv.transform(corpus_test).toarray()

# Parts of speech tag

In [9]:
print(tagged[0][0],'\n',tagged[0][1],'\n',tagged[0][2],'\n',tagged[0][3],'\n',tagged[0][4])


('said', 'VBD') 
 ('felt', 'JJ') 
 ('way', 'NN') 
 ('before,', 'NN') 
 ('suggeted', 'VBD')


# Applying Word2Vec

In [ ]:
# # Using Word2Vec
# from gensim.models import Word2Vec
# sentences_train = []
# sentences_test = []

In [ ]:
# # Cleaning data for Word2Vec in training dataset
# for i in range(len(train)):
#     review = re.sub('^a-zA-Z^',' ',train['text'][i])
#     review = review.lower()
#     review = review.split()
    
#     review = [word for word in review if word not in set(stopwords.words('english'))]
#     sentences_train.append(review)

In [ ]:
# # Cleaning data for Word2Vec in testing dataset
# for i in range(len(test)):
#     review = re.sub('^a-zA-Z^',' ',test['text'][i])
#     review = review.lower()
#     review = review.split()
    
#     review = [word for word in review if word not in set(stopwords.words('english'))]
#     sentences_test.append(review)

In [ ]:
# # Training Word2Vec
# train_model = Word2Vec(sentences_train, min_count=1)# if word is present less than 1 skip that word
# #test_model = Word2Vec(sentences_test, min_count=1)# if word is present less than 1 skip that word
# train_model.save("word2vec_train.model")
# #test_model.save("word2vec_test.model")

In [ ]:
# words_train = train_model.build_vocab(sentences_train)
# words_test = test_model.build_vocab(sentences_test)

In [ ]:
# # training word2vec
# train_model.train(sentences_train,total_examples=train_model.corpus_count,epochs=1001)# corpus_count =2838
# #test_model.train(sentences_test,total_examples=test_model.corpus_count,epochs=1001)

In [ ]:
# from gensim.models import KeyedVectors

# # Store just the words + their trained embeddings.
# word_vectors_train = train_model.wv
# word_vectors_train.save("word2vec.wordvectors")
# word_vectors_test = train_model.wv
# # word_vectors_test.save("word2vec.wordvectors")
# # Load back with memory-mapping = read-only, shared across processes.
# wv = KeyedVectors.load("word2vec_train.wordvectors", mmap='r')

# Training Logistic Regression Model on Training set

In [10]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state =0)
lr.fit(X_train,y_train)

LogisticRegression(random_state=0)

# Training K-NN Model on Training set

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
knn.fit(X_train,y_train)

KNeighborsClassifier()

# Training SVM Model on Training set

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf' , random_state=0)
classifier.fit(X_train,y_train)

SVC(random_state=0)

# Training Naive Bayes Model on Training set

In [13]:
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(X_train,y_train)

GaussianNB()

# Training Decision Tree Model on Training set

In [14]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state =0)
dtc.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Training Random Forest Model on Training set

In [15]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100 , criterion='entropy', random_state=0)
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

# Training XGBoost on Training set

In [16]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)

C:\Users\Dell\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:01:41] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

# Predicting the test set results

In [17]:
y_pred_lr = lr.predict(X_test)
y_pred_knn = knn.predict(X_test)
y_pred_classifier = classifier.predict(X_test)
y_pred_naive = naive.predict(X_test)
y_pred_dtc = dtc.predict(X_test)
y_pred_rfc = rfc.predict(X_test)
y_pred_xgb = xgb.predict(X_test)
# np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),axis=1)

# Making Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm_lr = confusion_matrix(y_test,y_pred_lr)
print('Logistic Regression : \n',cm_lr)
cm_knn = confusion_matrix(y_test,y_pred_knn)
print('K-NN : \n',cm_knn)
cm_classifier = confusion_matrix(y_test,y_pred_classifier)
print('SVM : ',cm_classifier)
cm_naive = confusion_matrix(y_test,y_pred_naive)
print('Naive Bayes : \n',cm_naive)
cm_dtc = confusion_matrix(y_test,y_pred_dtc)
print('Decision Tree Classifier : \n',cm_dtc)
cm_rfc = confusion_matrix(y_test,y_pred_rfc)
print('Random Forest Classifier : \n', cm_rfc)

print('\n')
print('Logistic Regression Classifier : \n')
print(classification_report(y_test,y_pred_lr))
print('K-Nearest Classifier : \n')
print(classification_report(y_test,y_pred_knn))
print('SVM Classifier : \n')
print(classification_report(y_test,y_pred_classifier))
print('Naive Bayes Classifier : \n')
print(classification_report(y_test,y_pred_naive))
print('Decision Tress Classifier : \n')
print(classification_report(y_test,y_pred_dtc))
print('Random Forest Classifier : \n')
print(classification_report(y_test,y_pred_rfc))


Logistic Regression : 
 [[236 110]
 [ 92 277]]
K-NN : 
 [[235 111]
 [200 169]]
SVM :  [[234 112]
 [ 95 274]]
Naive Bayes : 
 [[152 194]
 [ 97 272]]
Decision Tree Classifier : 
 [[174 172]
 [128 241]]
Random Forest Classifier : 
 [[188 158]
 [ 59 310]]


Logistic Regression Classifier : 

              precision    recall  f1-score   support

           0       0.72      0.68      0.70       346
           1       0.72      0.75      0.73       369

    accuracy                           0.72       715
   macro avg       0.72      0.72      0.72       715
weighted avg       0.72      0.72      0.72       715

K-Nearest Classifier : 

              precision    recall  f1-score   support

           0       0.54      0.68      0.60       346
           1       0.60      0.46      0.52       369

    accuracy                           0.57       715
   macro avg       0.57      0.57      0.56       715
weighted avg       0.57      0.57      0.56       715

SVM Classifier : 

             

# Hyperparameter Tuning the Models

# L

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
# Logistic Regression Model
param_grid = [    
    {'penalty' : ['l1', 'l2', 'elasticnet', 'none'],
    'C' : np.logspace(-4, 4, 20),
    'solver' : ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter' : [100, 300 ,500, 1000]
    }
]

In [21]:
clf = GridSearchCV(lr, param_grid = param_grid, cv = 3, verbose=True, n_jobs=-1)

In [ ]:
best_clf = clf.fit(X_train,y_train)

In [ ]:
print(clf.best_params_)

In [ ]:
best_clf.best_estimator_

In [ ]:
grid_predictions = clf.predict(X_test)

# print classification report
print(classification_report(y_test, grid_predictions))


In [ ]:
from sklearn.model_selection import GridSearchCV
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf', 'linear']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid.fit(X_train, y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
# print(grid.best_estimator_)

grid_predictions = grid.predict(X_test)

# print classification report
print(classification_report(y_test, grid_predictions))


# Using Stemming for the model

In [24]:
# Cleaning the data
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re

stemmer = PorterStemmer()
corpus_train_stem = []
corpus_test_stem = []

In [25]:
for i in range(len(train)):
    review = re.sub('^a-zA-Z^',' ',train['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_train_stem.append(review)

In [26]:
for i in range(len(test)):
    review = re.sub('^a-zA-Z^',' ',test['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))]
    tagged.append(tagger.tag(review))
    review = ' '.join(review)
    corpus_test_stem.append(review)

In [27]:
# Creating the Bag of Words

cv = CountVectorizer()
X_train_stem = cv.fit_transform(corpus_train_stem).toarray()
X_test_stem = cv.transform(corpus_test_stem).toarray()

In [28]:

lr = LogisticRegression(random_state =0)
lr.fit(X_train_stem,y_train)

LogisticRegression(random_state=0)

In [29]:

knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
knn.fit(X_train_stem,y_train)

KNeighborsClassifier()

In [30]:

classifier = SVC(kernel = 'rbf' , random_state=0)
classifier.fit(X_train_stem,y_train)

SVC(random_state=0)

In [31]:

naive = GaussianNB()
naive.fit(X_train_stem,y_train)

GaussianNB()

In [32]:

dtc = DecisionTreeClassifier(criterion = 'entropy', random_state =0)
dtc.fit(X_train_stem,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [33]:

rfc = RandomForestClassifier(n_estimators=100 , criterion='entropy', random_state=0)
rfc.fit(X_train_stem,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [34]:

xgb = XGBClassifier()
xgb.fit(X_train_stem,y_train)

C:\Users\Dell\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[16:22:07] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [35]:
y_pred_lr = lr.predict(X_test_stem)
y_pred_knn = knn.predict(X_test_stem)
y_pred_classifier = classifier.predict(X_test_stem)
y_pred_naive = naive.predict(X_test_stem)
y_pred_dtc = dtc.predict(X_test_stem)
y_pred_rfc = rfc.predict(X_test_stem)
y_pred_xgb = xgb.predict(X_test_stem)

In [36]:

cm_lr = confusion_matrix(y_test,y_pred_lr)
print('Logistic Regression : \n',cm_lr)
cm_knn = confusion_matrix(y_test,y_pred_knn)
print('K-NN : \n',cm_knn)
cm_classifier = confusion_matrix(y_test,y_pred_classifier)
print('SVM : ',cm_classifier)
cm_naive = confusion_matrix(y_test,y_pred_naive)
print('Naive Bayes : \n',cm_naive)
cm_dtc = confusion_matrix(y_test,y_pred_dtc)
print('Decision Tree Classifier : \n',cm_dtc)
cm_rfc = confusion_matrix(y_test,y_pred_rfc)
print('Random Forest Classifier : \n', cm_rfc)
cm_xgb = confusion_matrix(y_test,y_pred_xgb)
print('XGBoost Classifier : \n', cm_xgb)

print('\n')
print('Logistic Regression Classifier : \n')
print(classification_report(y_test,y_pred_lr))
print('K-Nearest Classifier : \n')
print(classification_report(y_test,y_pred_knn))
print('SVM Classifier : \n')
print(classification_report(y_test,y_pred_classifier))
print('Naive Bayes Classifier : \n')
print(classification_report(y_test,y_pred_naive))
print('Decision Tress Classifier : \n')
print(classification_report(y_test,y_pred_dtc))
print('Random Forest Classifier : \n')
print(classification_report(y_test,y_pred_rfc))

Logistic Regression : 
 [[241 105]
 [ 85 284]]
K-NN : 
 [[231 115]
 [197 172]]
SVM :  [[246 100]
 [ 97 272]]
Naive Bayes : 
 [[123 223]
 [ 97 272]]
Decision Tree Classifier : 
 [[185 161]
 [130 239]]
Random Forest Classifier : 
 [[195 151]
 [ 60 309]]
XGBoost Classifier : 
 [[222 124]
 [ 94 275]]


Logistic Regression Classifier : 

              precision    recall  f1-score   support

           0       0.74      0.70      0.72       346
           1       0.73      0.77      0.75       369

    accuracy                           0.73       715
   macro avg       0.73      0.73      0.73       715
weighted avg       0.73      0.73      0.73       715

K-Nearest Classifier : 

              precision    recall  f1-score   support

           0       0.54      0.67      0.60       346
           1       0.60      0.47      0.52       369

    accuracy                           0.56       715
   macro avg       0.57      0.57      0.56       715
weighted avg       0.57      0.56      0.

# Hyperparameter Tuning the Models 

In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Random Forest Classifier

In [70]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [71]:
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train_stem,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed: 10.6min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed: 50.7min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 103.1min finished


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [72]:
rf_randomcv.best_params_

{'n_estimators': 1400,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 1000,
 'criterion': 'entropy'}

In [73]:
rf_randomcv

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [74]:
best_random_grid=rf_randomcv.best_estimator_

In [75]:
rf_randomcv.best_params_

{'n_estimators': 1400,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 1000,
 'criterion': 'entropy'}

In [80]:
rf_Model = RandomForestClassifier(n_estimators= 1400,min_samples_split = 2,min_samples_leaf = 2,max_features = 'sqrt',max_depth = 1000,
 criterion = 'entropy')

In [81]:
rf_Model.fit(X_train_stem,y_train)

RandomForestClassifier(criterion='entropy', max_depth=1000, max_features='sqrt',
                       min_samples_leaf=2, n_estimators=1400)

In [83]:
y_pred_rand=rf_Model.predict(X_test_stem)
print(confusion_matrix(y_test,y_pred_rand))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_rand)))
print("Classification report: {}".format(classification_report(y_test,y_pred_rand)))

[[211 135]
 [ 68 301]]
Accuracy Score 0.7160839160839161
Classification report:               precision    recall  f1-score   support

           0       0.76      0.61      0.68       346
           1       0.69      0.82      0.75       369

    accuracy                           0.72       715
   macro avg       0.72      0.71      0.71       715
weighted avg       0.72      0.72      0.71       715



# SVM

In [89]:
parameters = [
    {
        'C' : [0.25, 0.5, 0.75],
        'kernel' : ['rbf'], 'gamma' : [0.1,0.01,0.001]
    }
]

In [109]:
svm_Model = SVC(C =0.25,kernel='rbf',gamma =0.01)

In [110]:
svm_Model.fit(X_train_stem,y_train)

SVC(C=0.25, gamma=0.01)

In [111]:
y_pred_svm = svm_Model.predict(X_test_stem)

In [112]:
print(confusion_matrix(y_test,y_pred_svm))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm)))

[[236 110]
 [103 266]]
Accuracy Score 0.7020979020979021
Classification report:               precision    recall  f1-score   support

           0       0.70      0.68      0.69       346
           1       0.71      0.72      0.71       369

    accuracy                           0.70       715
   macro avg       0.70      0.70      0.70       715
weighted avg       0.70      0.70      0.70       715



In [105]:
svm_Model2 = SVC(C =0.5,kernel='rbf',gamma =0.01)

In [106]:
svm_Model2.fit(X_train_stem,y_train)

SVC(C=0.5, gamma=0.01)

In [107]:
y_pred_svm2 = svm_Model2.predict(X_test_stem)

In [108]:
print(confusion_matrix(y_test,y_pred_svm2))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm2)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm2)))

[[247  99]
 [104 265]]
Accuracy Score 0.7160839160839161
Classification report:               precision    recall  f1-score   support

           0       0.70      0.71      0.71       346
           1       0.73      0.72      0.72       369

    accuracy                           0.72       715
   macro avg       0.72      0.72      0.72       715
weighted avg       0.72      0.72      0.72       715



In [143]:
svm_Model4 = SVC(C =0.5,kernel='rbf',gamma =0.02)

In [144]:
svm_Model4.fit(X_train_stem,y_train)

SVC(C=0.5, gamma=0.02)

In [145]:
y_pred_svm4 = svm_Model4.predict(X_test_stem)

In [146]:
print(confusion_matrix(y_test,y_pred_svm4))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm4)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm4)))

[[239 107]
 [100 269]]
Accuracy Score 0.7104895104895105
Classification report:               precision    recall  f1-score   support

           0       0.71      0.69      0.70       346
           1       0.72      0.73      0.72       369

    accuracy                           0.71       715
   macro avg       0.71      0.71      0.71       715
weighted avg       0.71      0.71      0.71       715



In [115]:
svm_Model3 = SVC(C =0.75,kernel='rbf',gamma =0.01)

In [116]:
svm_Model3.fit(X_train_stem,y_train)

SVC(C=0.75, gamma=0.01)

In [118]:
y_pred_svm3 = svm_Model3.predict(X_test_stem)

In [119]:
print(confusion_matrix(y_test,y_pred_svm3))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm3)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm3)))

[[250  96]
 [100 269]]
Accuracy Score 0.7258741258741259
Classification report:               precision    recall  f1-score   support

           0       0.71      0.72      0.72       346
           1       0.74      0.73      0.73       369

    accuracy                           0.73       715
   macro avg       0.73      0.73      0.73       715
weighted avg       0.73      0.73      0.73       715



In [131]:
svm_Model6 = SVC(C =0.75,kernel='rbf',gamma =0.02)

In [132]:
svm_Model6.fit(X_train_stem,y_train)

SVC(C=0.75, gamma=0.02)

In [133]:
y_pred_svm6 = svm_Model6.predict(X_test_stem)

In [134]:
print(confusion_matrix(y_test,y_pred_svm6))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm6)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm6)))

[[245 101]
 [ 95 274]]
Accuracy Score 0.7258741258741259
Classification report:               precision    recall  f1-score   support

           0       0.72      0.71      0.71       346
           1       0.73      0.74      0.74       369

    accuracy                           0.73       715
   macro avg       0.73      0.73      0.73       715
weighted avg       0.73      0.73      0.73       715



In [139]:
svm_Model7 = SVC(C =0.75,kernel='rbf',gamma =0.03)

In [140]:
svm_Model7.fit(X_train_stem,y_train)

SVC(C=0.75, gamma=0.03)

In [141]:
y_pred_svm7 = svm_Model7.predict(X_test_stem)

In [142]:
print(confusion_matrix(y_test,y_pred_svm7))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm7)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm7)))

[[235 111]
 [ 90 279]]
Accuracy Score 0.7188811188811188
Classification report:               precision    recall  f1-score   support

           0       0.72      0.68      0.70       346
           1       0.72      0.76      0.74       369

    accuracy                           0.72       715
   macro avg       0.72      0.72      0.72       715
weighted avg       0.72      0.72      0.72       715



In [147]:
svm_Model8 = SVC(C =1,kernel='rbf',gamma =0.01)

In [148]:
svm_Model8.fit(X_train_stem,y_train)

SVC(C=1, gamma=0.01)

In [149]:
y_pred_svm8 = svm_Model8.predict(X_test_stem)

In [150]:
print(confusion_matrix(y_test,y_pred_svm8))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm8)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm8)))

[[248  98]
 [ 97 272]]
Accuracy Score 0.7272727272727273
Classification report:               precision    recall  f1-score   support

           0       0.72      0.72      0.72       346
           1       0.74      0.74      0.74       369

    accuracy                           0.73       715
   macro avg       0.73      0.73      0.73       715
weighted avg       0.73      0.73      0.73       715



In [153]:
svm_Model9 = SVC(C =1,kernel='rbf',gamma =0.02)

In [154]:
svm_Model9.fit(X_train_stem,y_train)

SVC(C=1, gamma=0.02)

In [155]:
y_pred_svm9 = svm_Model9.predict(X_test_stem)

In [156]:
print(confusion_matrix(y_test,y_pred_svm9))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_svm9)))
print("Classification report: {}".format(classification_report(y_test,y_pred_svm9)))

[[246 100]
 [ 95 274]]
Accuracy Score 0.7272727272727273
Classification report:               precision    recall  f1-score   support

           0       0.72      0.71      0.72       346
           1       0.73      0.74      0.74       369

    accuracy                           0.73       715
   macro avg       0.73      0.73      0.73       715
weighted avg       0.73      0.73      0.73       715



# Naive Bayes

In [59]:
param_grid_nb = {
    'var_smoothing': np.logspace(0,-9, num=100)
}

In [60]:
naive_Model = GaussianNB()

In [61]:
nbModel_grid = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=10, n_jobs=-1)

In [62]:
nbModel_grid.fit(X_train_stem, y_train)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   16.3s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-1)]: Done 784 tasks      | elapsed:  5.8min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  7.3min finished


GridSearchCV(cv=10, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.848035...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             verbose=1)

In [63]:
nb_best_accuracy = nbModel_grid.best_score_

In [64]:
nb_best_parameters = nbModel_grid.best_params_

In [66]:
print (f'Train Accuracy - : {nbModel_grid.score(X_train_stem,y_train):.3f}')
print (f'Test Accuracy - : {nbModel_grid.score(X_test_stem,y_test):.3f}')

Train Accuracy - : 0.757
Test Accuracy - : 0.702


In [69]:
y_pred_nb = nbModel_grid.predict(X_test_stem)
print(confusion_matrix(y_test,y_pred_nb))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_nb)))
print("Classification report: {}".format(classification_report(y_test,y_pred_nb)))

[[206 140]
 [ 73 296]]
Accuracy Score 0.7020979020979021
Classification report:               precision    recall  f1-score   support

           0       0.74      0.60      0.66       346
           1       0.68      0.80      0.74       369

    accuracy                           0.70       715
   macro avg       0.71      0.70      0.70       715
weighted avg       0.71      0.70      0.70       715



# Logistic Regression

In [160]:
param_grid_lr = [
    {
     'penalty' : ['l1', 'l2'],
    'C' : np.logspace(-4, 4, 20),
    'solver' : ['liblinear']},
]

# Create grid search object

clf_lr = GridSearchCV(estimator=LogisticRegression(), param_grid = param_grid_lr, cv = 5, verbose=True, n_jobs=-1)

In [162]:
# Fit on data

best_clf_lr = clf_lr.fit(X_train_stem, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   32.8s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  1.1min finished


In [163]:
lr_best_accuracy = clf_lr.best_score_

In [164]:
lr_best_parameters = clf_lr.best_params_

In [165]:
print (f'Train Accuracy - : {clf_lr.score(X_train_stem,y_train):.3f}')
print (f'Test Accuracy - : {clf_lr.score(X_test_stem,y_test):.3f}')

Train Accuracy - : 0.874
Test Accuracy - : 0.740


In [167]:
y_pred_lr = clf_lr.predict(X_test_stem)
print(confusion_matrix(y_test,y_pred_lr))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred_lr)))
print("Classification report: {}".format(classification_report(y_test,y_pred_lr)))

[[243 103]
 [ 83 286]]
Accuracy Score 0.7398601398601399
Classification report:               precision    recall  f1-score   support

           0       0.75      0.70      0.72       346
           1       0.74      0.78      0.75       369

    accuracy                           0.74       715
   macro avg       0.74      0.74      0.74       715
weighted avg       0.74      0.74      0.74       715

